[workspace]
members = [
    "crates/ratchet-core",
    "crates/ratchet-integration-tests",
    "crates/ratchet-loader", 
    "crates/ratchet-models",
]
resolver = "2"

[profile.test]
debug = 2 
debug-assertions = true

[profile.release]
panic = 'abort'
lto = "fat"
codegen-units = 1
strip = true
#debug = 2

[workspace.dependencies]
wgpu = { version = "0.18.0", features = ["fragile-send-sync-non-atomic-wasm", "expose-ids"] }
anyhow = "1.0.40"
bytemuck = "1.14.0"
num-traits = "0.2.17"
half = { version = "2.3.1", features = ["num-traits", "bytemuck"] }
derive-new = "0.6.0"
log = "0.4.20"
thiserror = "1.0.56"
byteorder = "1.5.0"
