[package]
name = "ratchet-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratchet = { path = "../ratchet-core" }
ratchet-nn = { path = "../ratchet-nn" }
ratchet-loader = { path = "../ratchet-loader" }
byteorder.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
derive-new.workspace = true
log.workspace = true

[dev-dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wasm-bindgen-test = "0.3.41"
ratchet-client = { path = "../ratchet-client" }
wasm-bindgen = "0.2.91"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hf-hub = "0.3.2"

