[package]
name = "ratchet"
version = "0.1.0"
edition = "2021"

[features]
default = ["rand", "pyo3"]
pyo3 = ["dep:pyo3", "dep:numpy", "dep:ndarray"]
gpu_profiling = []
rand = ["dep:rand", "dep:rand_distr"]

[build-dependencies]
tera = "1.19.0"
thiserror = { workspace = true }
anyhow = { workspace = true }
globwalk = "0.8.1"

[dependencies]
wgpu = { workspace = true }
bytemuck = { workspace = true }
half = { workspace = true }
derive-new = { workspace = true }
num-traits = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
rustc-hash = "1.1.0"
slotmap = "1.0.7"
parking_lot = "0.12.1"
smallvec = "1.11.2"
encase = "0.7.0"
pollster = "0.3.0"
anyhow = "1.0.79"
num = "0.4.1"
rand_distr = { version = "0.4.3", optional = true }
rand = { version = "0.8.4", optional = true }
lazy_static = "1.4.0"

# Python bindings
pyo3 = { version = "0.20.2", features=["auto-initialize"], optional = true }
numpy = { version = "0.20.0", optional = true }
ndarray = { version = "0.15.6", optional = true }

[dev-dependencies]
rand = "0.8.4"
pyo3 = { version = "0.20.2", features=["auto-initialize"] }
numpy = { version = "0.20.0" }
ndarray = { version = "0.15.6" }
regex = "1.10.3"
test-strategy = "0.3.1"
proptest = "1.4.0"

