name: Ratbot
on:
  pull_request_target

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the lines of code.
        id: scc
        uses: Adapt-API/scc-docker-action@master
        with:
          args: ${{ env.workspace }} -irs --exclude-file kernels

      # Step to comment on the PR
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const codeReport = '${{ steps.loc.outputs.lines }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${codeReport`
            })

