name: Ratbot
on:
  pull_request_target

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2 
        with:
          args: ${{ env.workspace }} -irs 

      #TODO:
      #Add model performance benchmarks
      #Update comment to avoid noise

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const codeReport = "\\`\\`\\`\\n" +
            ${{ steps.scc.outputs.scc }} +
            "\\n\\`\\`\\`";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${codeReport}`
            })

