name: Ratbot
on:
  pull_request_target

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the lines of code
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2 
        with:
          args: ${{ env.workspace }} -irs 

      - name: Write output to a file
        run: |
          echo "${{ steps.scc.outputs.scc }}" > scc_output.txt

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sccOutput = fs.readFileSync('scc_output.txt', 'utf8');
            const codeReport = `
              <details>
              <pre>
              ${sccOutput}
              </pre>
              </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: codeReport
            });

